### PR TITLE
Mark PyjionSettings as `extern` to use as a global

### LINKED ISSUE #167: set_optimization_level is not working
The `pyjion.set_optimization_level)` function seems to have little or no effect

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Closes #167.

### CODE REVIEW

File: src/pyjion/pyjit.h [hunk 1]
```diff
@@ -83,7 +83,7 @@ static PY_UINT64_T HOT_CODE = 0;
 static PY_UINT64_T jitPassCounter = 0;
 static PY_UINT64_T jitFailCounter = 0;
 
-static PyjionSettings g_pyjionSettings;
+extern PyjionSettings g_pyjionSettings;
```
Comment (tetsuo-cpp) [inline src/pyjion/pyjit.h:86]: My understanding is that each TU that included `pyjit.h` had its own `g_pyjionSettings`. If we mark it as `extern` and then declare it in `pyjit.cpp`, they should all be reading from and writing to the same memory.

Comment (tonybaloney) [reply src/pyjion/pyjit.h:86]: awesome! thanks. I wanted to update some of the unit tests to verify that some `assertOptimized` is the opposite when the level is 0
